### ISSUE TITLE
Updating financial type has error in sql code

### ISSUE THREAD

**Issue by jmcclelland** [lcdservices/biz.lcdservices.movecontrib#10]
Thanks for this extension. I was preusing it before manually moving a few contributions between contacts and I noticed what looks like a bug.

https://github.com/lcdservices/biz.lcdservices.movecontrib/blob/3f45fbfc4816a1b722c4c7b4d0b5e12e38b49ebb/CRM/LCD/MoveContrib/BAO/MoveContrib.php#L24

I'm pretty sure that should be `%2` instead of `%1` although I haven't tested a fix or even encountered a problem.

**Comment by lcdservices** [comment]
Agreed. I've fixed it and pushed up a new version.
