### ISSUE TITLE
installing on 5.60 site results in error

### ISSUE THREAD

**Issue by jmcclelland** [lcdservices/biz.lcdservices.movecontrib#13]
The error is:

> Error: Class 'CRM_LCD_MoveContrib_Upgrader_Base' not found in _movecontrib_civix_upgrader() (line 203 of /xxxx/sites/all/extensions/biz.lcdservices.movecontrib/movecontrib.civix.php).

**Comment by jmcclelland** [comment]
I fixed it by running `civix upgrade`. I tried to commit my changes by accidentally pushed the wrong repo - I can work on this tomorrow if you'd like a PR.

**Comment by lcdservices** [comment]
I've run the upgrade and that class has now been removed. Version updated to 2.7.
thanks!
