### ISSUE TITLE
DB Error: syntax error

### ISSUE THREAD

**Issue by tapashdatta** [lcdservices/biz.lcdservices.movecontrib#14]
On civi 5.61, Upgraded from v2.2 to v2.7. despite giving permission receiving DB Error: syntax error

**Comment by MegaphoneJon** [comment]
@tapashdatta Could you please give a full debug and backtrace for that error?  There's not enough information to troubleshoot this.

**Comment by lcdservices** [comment]
@tapashdatta Yes, please provide more details. I just installed the extension on a clean site running 5.61 and am not getting any errors when moving contribs.

**Comment by tapashdatta** [comment]
@lcdservices Apologies! Seems it’s one of my conflicting custom extension. Thanks anyway.
