### ISSUE TITLE
DB error if no user selected

### ISSUE THREAD

**Issue by twomice** [lcdservices/biz.lcdservices.movecontrib#15]
If a user like me wants to be stupid, they could try and move a contribution without selecting a contact.  This yields a frozen screen in the pop-up, caused by a DB fatal error.

Repro:

1. Select a contribution to move and click "Move Contribution". Observe that the "Move ContributIon" pop-up appears.
2. In the "Select Contact" field, do nothing -- leave it blank.
3. Click "Submit"
4. Observe that the pop-up gets stuck in the "loading" state; this is typical when a civicrm pop-up hits an error on the server side.

Alternate repro:

1. Select a contribution to move and use right-click to open the "Move Contribution" in a new tab/window. Observe that the "Move ContributIon" form appears as a full page.
2. In the "Select Contact" field, do nothing -- leave it blank.
3. Click "Submit"
4. Observe fatal error: "Sorry, due to an error, we are unable to fulfill your request at the moment. You may want to contact your administrator or service provider with more details about what action you were performing when this occurred. DB Error: constraint violation"

Suggestion: make the "Select Contact" field required in this form.

**Comment by lcdservices** [comment]
fixed.

**Comment by twomice** [comment]
Thanks @lcdservices !
