### ISSUE TITLE
Move subscription

### ISSUE THREAD

**Issue by masetto** [lcdservices/biz.lcdservices.movecontrib#19]
@lcdservices, my client asked me to develop the "move subscription" functionality. Instead of making a new extension, what do you think about integrating it into this one?

**Comment by masetto** [comment]
oops, I realized that you have already done the [extension](https://github.com/lcdservices/biz.lcdservices.movemembership).
I fork it because there are some incompatibilities with the current version of CiviCRM.

**Comment by lcdservices** [comment]
so by "subscription" you meant membership?
feel free to submit a PR with compatibility fixes. open a new ticket with the details of the issues you found.
