### ISSUE TITLE
Smarty 4 causes blank pop up

### ISSUE THREAD

**Issue by guyiac** [lcdservices/biz.lcdservices.movecontrib#23]
Brian:

I'm getting a blank pop up when we try to move a contribution. This system is currently on Civi 5.74.5, WordPress 6.6.1, Smarty 4. When we disable Smarty 4, it works. 

The message in the log is: 

[warning] Permission 'allow Move Contribution' should be declared with 'label' and 'description' keys. See https://docs.civicrm.org/dev/en/latest/hooks/hook_civicrm_permission/ Caller: CRM_Core_Permission::assembleBasicPermissions
Array
(
    [civi.tag] => deprecated
)

Any thoughts?

**Comment by lcdservices** [comment]
@guyiac make sure you're running the latest version of this extension -- 2.12. 
The permission issue was fixed a version or two ago, and I just tested it on a WP demo site with Smarty 4 enabled and the popup worked as expected with the select contact field exposed.

**Comment by guyiac** [comment]
That did it, thank you.

**Comment by eileenmcnaughton** [comment]
@guyiac @lcdservices - this can be closed I think
