### ISSUE TITLE
Update "<releaseDate>" tag in info.xml (future releases only)

### ISSUE THREAD

**Issue by twomice** [lcdservices/biz.lcdservices.movecontrib#6]
Hi @lcdservices This isn't something you could fix in previous releases, but next time you tag a release, I recommend updating the `<releaseDate>` tag in `info.xml` to the current date, so that the release is shown as current in the Extension Directory.  At present, all releases at https://civicrm.org/extensions/move-contribution are showing a release date of "2016-08-30 - 12:00", which probably makes potential users think the code is quite old, even though we can see at https://github.com/lcdservices/biz.lcdservices.movecontrib/tags that all of them were made on or after April 4, 2018 (and the most recent one was just last month).

You can probably just close this issue now, but I thought a ticket might be the easiest way to make this suggestion.

(Great extension by the way; I've just installed it now and it work quite nicely for what I need.)

**Comment by lcdservices** [comment]
thanks for the suggestion -- I'll make a point of doing that with all extensions in future releases!
